name: continuous-intergration/examples

on:
  push:
    branches:
      - master
    tags:
        - v*
    paths-ignore:
      - 'README.md'
      - '.gitlab-ci.yml'
  pull_request:
    branches:
      - master
    paths:
      - '.github/workflows/examples.yml'

jobs:
  check:
    name: examples
    strategy:
      matrix:
        platform:
          - macos-latest
          - windows-latest
        toolchain:
          - nightly
        job:
          - build
          - test
        contract:
          - examples/delegator/accumulator
          - examples/delegator/adder
          - examples/delegator/subber
          - examples/delegator
          - examples/contract-transfer
          - examples/contract-terminate
          - examples/dns
          - examples/erc1155
          - examples/erc20
          - examples/erc721
          - examples/flipper
          - examples/incrementer
          - examples/multisig
          - examples/proxy
          - examples/rand-extension
          - examples/trait-erc20
          - examples/trait-flipper
          - examples/trait-incrementer
    runs-on: ${{ matrix.platform }}
    env:
      RUST_BACKTRACE: full
    steps:

      - uses: actions/setup-node@v2
      - run: npm install wasm-opt -g

      - name: Checkout sources & submodules
        uses: actions/checkout@master
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Install toolchain
        id: toolchain
        uses: actions-rs/toolchain@master
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          components: rust-src
          override: true

      - name: Rust Cache
        uses: Swatinem/rust-cache@v1.2.0

      - name: Install `cargo-contract` `master`
        uses: actions-rs/cargo@v1
        with:
            command: install
            args: --git https://github.com/paritytech/cargo-contract.git

      - name: Output versions
        run: |
            wasm-opt --version
            cargo -vV
            cargo contract --version

      - name: ${{ matrix.job }} examples on ${{ matrix.platform }}-${{ matrix.toolchain }}-${{ matrix.contract }}
        if: runner.os == 'Windows'
        run: |
            echo "Processing delegator contract: ${{ matrix.contract }}";
            cargo contract ${{ matrix.job }} --verbose --manifest-path ${{ matrix.contract }}/Cargo.toml;

      - name: ${{ matrix.job }} examples on ${{ matrix.platform }}-${{ matrix.toolchain }}-${{ matrix.contract }}
        if: runner.os == 'macOS'
        run: |
            echo "Processing delegator contract: ${{ matrix.contract }}";
            cargo contract ${{ matrix.job }} --verbose --manifest-path ${{ matrix.contract }}/Cargo.toml;
